name: DevSecOps Pipeline
on: [push, pull_request]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # SAST: Semgrep (updated to v2)
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v2  # Updated from v1
        with:
          config: p/security-audit  # Updated ruleset

      # SCA: OWASP Dependency-Check (official action)
      - name: OWASP Dependency-Check
        uses: dependency-check/dependency-check-action@v3  # Updated action
        with:
          project: 'secure-cicd-demo'
          format: 'HTML'
          fail_on_cvss: 8  # Fail on high/critical CVEs

      # Secrets Detection (TruffleHog with direct install)
      - name: Scan for Secrets
        run: |
          pip install trufflehog
          trufflehog git --no-update file://$(pwd) --only-verified --json

      # Container Security (Trivy)
      - name: Scan Docker Image
        run: |
          docker build -t my-app .
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image --exit-code 1 --severity CRITICAL my-app

  deploy:
    needs: security-checks
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment would happen here after security checks pass!"